### PR TITLE
Add ability to retrieve and tell wrapper to validate distribution checksums

### LINKED ISSUE #44: distribution checksum option
Please add an option to set distribution checksum inside `gradle-wrapper.properties`

### PR DESCRIPTION
**Pull request by chadlwilson**
Fixes #44

- Adds a new `validate-distribution-checksum` option (defaults to `false`)
- Retrieves checksums from appropriate `distributions` location on `services.gradle.org`. Relying on TLS cert validation for integrity of the checksums is about as good as we can get, as there don't seem to be signatures available.

**Changes**
One semantic change I made is to hard-code the default distribution to `bin`. The reason for this is that running `./gradlew wrapper` without an arg is inconsistent, and will override back to `bin` regardless of the existing `gradle-wrapper.properties` value. That makes it impossible to use this right now for `all` distributions. To solve this we need to pass a value to `--distribution-type` which means the action needs to now the default. To retain backward compatibility for the action, I have kept around the `default` option though.

**Known weaknesses**
- Unfortunately the URL construction somewhat couples the action to the distribution URL calculation logic _inside_ the wrapper, since Gradle doesn't provide a mechanism inside the wrapper to detect new versions and/or checksums and find them via `services.gradle.org`. Arguably it **might** be more consistent to switch this action to using `gradle-distribution-url` to update the wrapper (rather than `--gradle-version` and `--distribution-type`) to ensure consistency. Let me know if you'd rather we take this approach and I'll update the PR.
- It is not possible to use this action alone to raise PRs that **disable** checksum validation if the wrapper is previously using it. This is intentional to ensure people make a separate commit to remove the checksums from their `gradle-wrapper.properties` rather than this action "accidentally" doing so.

**TODO**
- [ ] Update the github actions tests

### CODE REVIEW

**Comment by EdwarDDay** [comment]
I integrated the `default` option for the `distribution-type` for users, who want to define it in the [build.gradle file](https://docs.gradle.org/current/userguide/gradle_wrapper.html#customizing_wrapper). Maybe it's better to return an error, when `validate-distribution-checksum` is activated but `distribution-type` is not set.

**Comment by chadlwilson** [comment]
The problem with using `./gradlew` without a distribution type in the second invocations, affects running without validating the checksums too, I believe, but will double check

**Comment by chadlwilson** [comment]
Yeah, the same problem exists without distribution type - i.e with the action as it currently stands since it has the flow

```shell
./gradlew wrapper <ARGS>
./gradlew wrapper # <----- resets distribution-type to default (bin)
```

image

The problem is more "detectable" with the checksums because when it switches back to `bin` the wrapper does not wipe the checksum property, so you get a checksum mismatch.

For me, there are two options
1. If the action takes the `distribution-type` as an arg, I think it should be able to switch distributions.
2. If there is no need to "switch" distributions the action could be simpler and just read/infer the distribution from the existing `gradle-wrapper.properties` by looking at the `distributionUrl`. (dodgy URL parsing notwithstanding....)

> I integrated the `default` option for the `distribution-type` for users, who want to define it in the [build.gradle file](https://docs.gradle.org/current/userguide/gradle_wrapper.html#customizing_wrapper). 

Ahh thanks for this, I had forgotten this was a possible configuration. Let me re-think and see how that works.

Generally speaking, are you interested to continue with this PR if I can resolve issues/concerns?

**Comment by EdwarDDay** [comment]
> Generally speaking, are you interested to continue with this PR if I can resolve issues/concerns?

Yes, of course. Thank you for your contribution.

**Comment by chadlwilson** [comment]
I've kind of abandoned this for now, because an alternate github action available already supports checksum and wrapper jar checksum validation; does the double-runs necessary etc.

**Pull request closed without merging**
